# Schema Bifrost pour le site demo
# Ce schema definit tous les champs editables du site

fields:

  hero.logo:
    type: image
    label: "Logo"

  hero.title:
    type: text
    label: "Titre principal"

  hero.subtitle:
    type: text
    label: "Sous-titre"

  hero.cta:
    type: text
    label: "Texte du bouton"


  features.title:
    type: text
    label: "Titre section services"

  features.feature1.title:
    type: text
    label: "Service 1 - Titre"

  features.feature1.description:
    type: text
    label: "Service 1 - Description"

  features.feature2.title:
    type: text
    label: "Service 2 - Titre"

  features.feature2.description:
    type: text
    label: "Service 2 - Description"

  features.feature3.title:
    type: text
    label: "Service 3 - Titre"

  features.feature3.description:
    type: text
    label: "Service 3 - Description"


  testimonials.title:
    type: text
    label: "Titre section temoignages"

  about.title:
    type: text
    label: "Titre A propos"

  about.description:
    type: richtext
    label: "Description A propos"


  contact.title:
    type: text
    label: "Titre contact"

  contact.subtitle:
    type: text
    label: "Sous-titre contact"

  contact.email:
    type: text
    label: "Email de contact"


  footer.copyright:
    type: text
    label: "Copyright"


collections:
  testimonials:
    label: "Temoignages"
    fields:
      quote:
        type: text
        label: "Citation"

      name:
        type: text
        label: "Nom"

      role:
        type: text
        label: "Poste et entreprise"

      initials:
        type: text
        label: "Initiales"
